#ifndef YK_POLYFILL_CONFIG_HPP
#define YK_POLYFILL_CONFIG_HPP

// TODO: DELETE THIS BEFORE RELEASE
#define YK_POLYFILL_NO_STD

#ifdef YK_POLYFILL_NO_STD

#define YK_POLYFILL_NO_STD_INTEGER_SEQUENCE

#endif

#endif  // YK_POLYFILL_CONFIG_HPP
